apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: bshraib/fakelook-auth:2.0
          # resources:
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
          #   requests:
          #     cpu: "250m"
          #     memory: "256Mi"
          env:
            - name: PORT
              value: "5000"
            - name: IDENTITY_SERVICE
              value: "http://identity-srv:5001/api"
            - name: DATA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-urls-config
                  key: AUTH_DB_URL
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: TOKEN_SECRET
          readinessProbe:
            httpGet:
              path: "/health-check"
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 5000
      targetPort: 5000
