apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mendelovic/fakelook-auth
          ports:
            - containerPort: 5000
          env:
            - name: IDENTITY_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: fakelook-configmap
                  key: identity_url
            - name: DATA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: auth_db_url
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: fakelook-secret
                  key: acces_token_key
            - name: ACCESS_TOKEN_EXPIRES_IN
              value: "3600"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
