apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  auth_db_url: bW9uZ29kYitzcnY6Ly9tZW5kZWxvdmljOjRxMUJOT0JlZFdCbUNLNGxAY2x1c3RlcjAuOTh4cHkzby5tb25nb2RiLm5ldC9hdXRoP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  identity_db_url: bW9uZ29kYitzcnY6Ly9tZW5kZWxvdmljOjRxMUJOT0JlZFdCbUNLNGxAY2x1c3RlcjAuOTh4cHkzby5tb25nb2RiLm5ldC9pZGVudGl0eT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  post_db_url: bW9uZ29kYitzcnY6Ly9tZW5kZWxvdmljOjRxMUJOT0JlZFdCbUNLNGxAY2x1c3RlcjAuOTh4cHkzby5tb25nb2RiLm5ldC9wb3N0P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  feed_db_url: bW9uZ29kYitzcnY6Ly9tZW5kZWxvdmljOjRxMUJOT0JlZFdCbUNLNGxAY2x1c3RlcjAuOTh4cHkzby5tb25nb2RiLm5ldC9mZWVkP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
