apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - name: feed
          image: bshraib/fakelook-feed:2.0
          env:
            - name: port
              value: "5003"
            - name: DATA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-urls-config
                  key: FEED_DB_URL
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: TOKEN_SECRET
            - name: AMQP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: message-broker
                  key: AMQP_SERVER
            - name: "NODE_CONFIG_DIR"
              value: "/app/src/config/"
          readinessProbe:
            httpGet:
              path: "/health-check"
              port: 5003
            initialDelaySeconds: 10
            timeoutSeconds: 5
          # resources:
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
          #   requests:
          #     cpu: "250m"
          #     memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: feed-srv
spec:
  selector:
    app: feed
  ports:
    - name: feed
      protocol: TCP
      port: 5003
      targetPort: 5003
