apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: bshraib/fakelook-identity:2.0
          env:
            - name: AUTH_SERVICE
              value: "http://auth-srv:5000/api"
            - name: URL_DB_CONECTION
              valueFrom:
                configMapKeyRef:
                  name: db-urls-config
                  key: IDENTITY_DB_URL
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: TOKEN_SECRET
            - name: AMQP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: message-broker
                  key: AMQP_SERVER
---
apiVersion: v1
kind: Service
metadata:
  name: identity-srv
spec:
  selector:
    app: identity
  ports:
    - name: identity
      protocol: TCP
      port: 5001
      targetPort: 5001
