apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: bshraib/fakelook-identity:1.0.0
          env:
            - name: AUTH_SERVICE
              value: "https://auth-srv:5000"
            - name: URL_DB_CONECTION
              value: "mongodb+srv://mendelovic:4q1BNOBedWBmCK4l@cluster0.98xpy3o.mongodb.net/identity?retryWrites=true&w=majority"
            - name: TOKEN_SECRET
              value: "veryverysecretkey"
          readinessProbe:
            httpGet:
              path: "/health-check"
              port: 5001
            initialDelaySeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: identity-srv
spec:
  selector:
    app: identity
  ports:
    - name: identity
      protocol: TCP
      port: 5001
      targetPort: 5001
