apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: mendelovic/fakelook-post
          ports:
            - containerPort: 5002
          env:
            - name: DATA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: post_db_url
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: fakelook-secret
                  key: acces_token_key
            - name: AMQP_SERVER
              valueFrom:
                secretKeyRef:
                  name: fakelook-secret
                  key: amqp_server
            - name: GCLOUD_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: fakelook-configmap
                  key: google_storage
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
