apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: bshraib/fakelook-post:2.0
          env:
            - name: DATA_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-urls-config
                  key: POST_DB_URL
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: token-secret
                  key: TOKEN_SECRET
            - name: AMQP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: message-broker
                  key: AMQP_SERVER
            - name: GCLOUD_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: storage-config
                  key: GCLOUD_STORAGE_BUCKET
---
apiVersion: v1
kind: Service
metadata:
  name: post-srv
spec:
  selector:
    app: post
  ports:
    - name: post
      protocol: TCP
      port: 5002
      targetPort: 5002
